spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/journapi
    username: devuser
    password: devpass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration/common,classpath:/db/migration/dev